version: '3.1'
name: 'pruebatecnica'

services:

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}" 
      POSTGRES_PASSWORD: "${DB_PASS}"
      TZ: "UTC"   
